name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/cv.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.run_number }}
          files: |
            cv.pdf
